# Generated by Django 4.1.5 on 2023-04-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corto',
            name='imagen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='corto',
            name='puntuacion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='corto',
            name='sinopsis',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='corto',
            name='video',
            field=models.CharField(default='', max_length=100),
        ),
    ]
