# Generated by Django 4.1.5 on 2023-05-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimad_app', '0002_alter_corto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corto',
            name='video',
            field=models.FileField(blank=True, default='', upload_to='videos/'),
        ),
    ]
