# Generated by Django 4.1.5 on 2023-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimad_app', '0003_alter_corto_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='corto',
            name='fecha_pagina',
            field=models.DateField(null=True),
        ),
    ]
